### ISSUE TITLE
Add .clang-format

### ISSUE THREAD

**Issue by qbradq** [dungeons-of-moria/umoria#1]
Thank you so much for the 5.7 release! Great work. Can you please add a .clang-format file containing the formatting options used to format the source code? This will allow other developers to maintain the existing style while hacking on the code base. If you did not use such a file during the conversion you can create one by using the same clang-format cli options ending with "-dump > .clang-format" I think.

**Comment by mrcook** [comment]
Hi, I didn't specify a file during the formatting but I'll certainly look into it for you. Thanks for the feedback.
