### ISSUE TITLE
Build failed on GCC 8.1

### ISSUE THREAD

**Issue by BPaden** [dungeons-of-moria/umoria#17]
```
/home/aaron/Documents/source-packages/umoria/src/umoria-5.7.10/src/dungeon_los.cpp: In function ‘bool lookSee(int, int, bool&)’:
/home/aaron/Documents/source-packages/umoria/src/umoria-5.7.10/src/dungeon_los.cpp:530:37: error: ‘%s’ directive writing up to 159 bytes into a region of size between 149 and 152 [-Werror=format-overflow=]
                 (void) sprintf(msg, "%s %s ---pause---", description, obj_string);
                                     ^~~~~~~~~~~~~~~~~~~               ~~~~~~~~~~
/home/aaron/Documents/source-packages/umoria/src/umoria-5.7.10/src/dungeon_los.cpp:530:31: note: ‘sprintf’ output between 21 and 183 bytes into a destination of size 160
                 (void) sprintf(msg, "%s %s ---pause---", description, obj_string);
                        ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

Looks like the issue is that obj_string is the same size as msg, so it seems to the compiler like there would be an overflow here. If I make msg larger, I get similar errors elsewhere, and so on. Seems like a common pattern.

**Comment by mrcook** [comment]
Thanks for report Aaron. Back when I was adding the compiler warnings I encountered an issue related to this, and realised that to update these would be a big task!

I've not yet updated to GCC 8, so I'll take a look over the weekend to see if I can figure something out to get it compiling.

Cheers,
Michael

**Comment by mrcook** [comment]
I took some time yesterday to look over this again, and as I feared, the refactoring and testing required is quite considerable. For now you can temporarily disable the warnings to let you compile on GCC8. Insert the following at line `#62` in `CMakeList.txt`:

```
set(cxx_warnings "${cxx_warnings} -Wno-error=format-overflow")
set(cxx_warnings "${cxx_warnings} -Wno-format-overflow")
```

For some reason these cause an error with `clang` on macOS, so I'm not able to commit those changes to the repo.

I'm currently on a hiatus from any major refactoring work on Umoria, but I'll leave this issue open so others will more easily find the fix, as well as a reminder to myself for when I get back on the project!

**Comment by BPaden** [comment]
It looks like you can wrap a conditional around that like

```
if ("${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
    set(cxx_warnings "${cxx_warnings} -Wno-error=format-overflow")
    set(cxx_warnings "${cxx_warnings} -Wno-format-overflow")
endif ()
```

**Comment by mrcook** [comment]
Nice! This actually got me thinking if it would be possible to check for the compiler:

```
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "GNU")
endif()
```

It seems so, and with luck this will also work on macOS. I'll give it a go when I get a chance.

Thanks Aaron!

**Comment by mrcook** [comment]
Change has been made and compiling now works on GCC 8: https://github.com/dungeons-of-moria/umoria/commit/ae674939bade12e82a2d7f04ada5b94dc4edc62b

I've only managed to test this on macOS, but I see no reason it will not work on Linux too.

Thanks again for your help Aaron, it's much appreciated.

Michael

**Comment by BPaden** [comment]
Nice, can confirm this works on Linux as well, thank you.

**Comment by mrcook** [comment]
Great! Happy to hear it works.
