### ISSUE TITLE
STR variable not behaving properly for Elf mage

### ISSUE THREAD

**Issue by aladdin1404** [dungeons-of-moria/umoria#2]
Running an Elf Mage in uMoria 5.7 and STR has always been 4 despite having been bitten by a variety red beasties which say they have "weakened" my Elf numerous times. I was thinking that 4 must be the minimum STR value. Today I found a Ring of Strength (+1) but once I put this ring on, my STR value was reduced to 2. Thinking this ring was cursed, I took it off but STR was reduced to 1. This made carrying my wands etc very difficult as the load exceeded my strength. Putting the ring back on made STR 2 again.
Looks like a bug to me.

**Comment by mrcook** [comment]
Hi aladdin1404, many thanks for the report, it certainly seems odd behaviour. I'll take a look at this as soon as I'm able and post back here what I find out -- it's going to be some days though as I'm very busy for the remainder of this week.

**Comment by aladdin1404** [comment]
Hi mrcook, thanks for looking into this problem. I am using version 5.7.0. I will see if I can find 5.7.3. and test if the issue still exists.

**Comment by aladdin1404** [comment]
Have installed version 5.7.3 and have run the game with the same ,sav file I was using with 5.7.0. Note I am running the 64bit version under Windows 10. In that game, the STR var is 4 and I had just found a Potion of Strength. So now running 5.7.3, I consumed the Potion of Strength and my STR is now 2, I repeated this test by returning to Town level with the Potion of Strength, and purchased a potion of restore strength. Drinking the restore potion did nothing and STR remained 4. Drinking the Potion of Strength reduced STR to 2. I had exactly the same result in 5.7.0.

**Comment by mrcook** [comment]
Thanks for the info. Would there be a possibility of you sharing your save file with me? That would help speed up the debugging. You can either attach it here, or if you'd rather, please feel free to email it to me: info@umoria.org.

Many thanks, Michael.

**Comment by aladdin1404** [comment]
Attached is my .sav file in zip format (couldn't attach as .sav)
[game.zip](https://github.com/dungeons-of-moria/umoria/files/1134107/game.zip)

**Comment by mrcook** [comment]
I made some exploration and found an unexpected value in `py.stats.cur_stat[]` regarding the strength (i.e. not `4`). To double check if I'd actually introduced a bug I set up an Virtual Machine running Ubuntu to test against the original Umoria 5.6 (installed via `apt-get`).

Loading up your save file I encountered the same behaviour. `STR` starts at `4`, I quaff one of the *Potions of Strength* and the strength drops to `2`. Quaffing the next two potions takes the `STR` up to `3` and then `4`.

At the very least we know this behaviour has been around for a while, but of course it would be nice to figure out exactly what is happening here. After some consideration though I've decided to close this issue for now. I will of course make a note and at some point in the future I'll take another look at this to figure exactly what is going on.

Thanks again for taking the time to make this report aladdin1404.

**Comment by aladdin1404** [comment]
I think it might be important to remember that the STR var. didn't decrement when my mage was bitten by a red creature, though I saw the message about being "weakened". But it appears that such bites are "remembered" somewhere, possibly in the sav file, and have effect when a Ring of Strength or Potion of Strength is used.  So maybe my .sav file might have been "corrupted" by 5.7.0 and the incorrect behaviour was seen in 5.6 due to my .sav file.

I am not new to this game and haven't seen this problem before.

**Comment by mrcook** [comment]
Thanks for the update, this certainly adds more light on the issue, and if you've never seen this behaviour before then this certainly warrants more investigation. I'm reopening and will take another look.

**Comment by aladdin1404** [comment]
Thanks MrCook. I can also tell you that I have definitely lost, restored and increased DEX successfully during this game.

**Comment by mrcook** [comment]
Hi aladdin1404,

I've tried numerous times to figure out what's going on here but without luck. As I noted earlier, this issue still happens in the original Umoria 5.6, and to double check if anything strange was being saved in the `game.sav` I wrote a saved game viewer, but from what I can see nothing particularly seems wrong. One thing that might be worth looking into further is that your overall stats are quite low:
```
Max Stats: [ 1, 54, 17, 46]
Cur Stats: [ 1, 54, 17, 46]
Mod Stats: [ 0,  0,  0,  0]
Use Stats: [ 4, 54, 17, 46]
```
`STR` is the first entry in each of those stats.

I'll to do a little more digging, but wanted to give you an update in the meantime.

**Comment by aladdin1404** [comment]
Thanks, the update is appreciated. 
I have created a new elf mage from scratch in Umoria 5.6 and can confirm that the incorrect behaviour does exist in this version. This elf had an initial STR of 3. I sought out a red frog who bit my elf twice. Both times I received a message that my elf had been weaken, but the STR value wasn't decremented. Not having a Ring of Strength or Potion of Strength, I didn't test this elf any further. It is many years since I last killed a Balrog, and have no idea what version of UMoria I was running, but this behaviour didn't exist back then.

**Comment by mrcook** [comment]
Thanks for the update, and many thanks for taking the time to experiment further with this issue!

I've just had a look over the code changes for the different versions and could see nothing in the `5.6` release that would create issues like this - that release was mostly text and compilation changes. Even in the `5.5.2` release I couldn't see anything obvious, and that version was released in 1994.

Considering this information it's probably safe to close this issue. If it's a bug, it's been around a long time, and for the moment I don't want to (_knowingly_) make gameplay changes.
