### ISSUE TITLE
Program fails to compile on Fedora 32 Linux

### ISSUE THREAD

**Issue by alsusrus** [dungeons-of-moria/umoria#30]
/home/alansmith/Documents/umoria/umoria-master/src/ui_io.cpp:613:17: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
  613 |         user[i] = '\0';
      |         ~~~~~~~~^~~~~~
/home/alansmith/Documents/umoria/umoria-master/src/ui_io.cpp:604:14: note: at offset 128 to object ‘user’ with size 128 declared here
  604 |         char user[128];
      |              ^~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/umoria.dir/build.make:720: CMakeFiles/umoria.dir/src/ui_io.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/umoria.dir/all] Error 2
make: *** [Makefile:104: all] Error 2

I get this error when trying to compile the program on fedora 32. Is there a workaround available to fix this and let the program finish compiling?

**Comment by supersnail12345** [comment]
@alsusrus 
It looks to me like the segment of code between lines 604 and 613 of ui_io.cpp allow the value of 'i' to reach 128, which overflows the array:

        char user[128];
        struct passwd *pw = nullptr;
        int i = 0;

        user[0] = '\0';
        file++;
        while (*file != '/' && i < (int) sizeof(user)) {
            user[i++] = *file++;
        }
        user[i] = '\0';

The while loop allows i to reach exactly 127, which means that attempting to write '\0' into the array at offset 128 overflows the array. You could try changing line 610 to **i < (int) sizeof(user)-1**

@mrcook this might be fixable by changing it to 1 less than **sizeof(user)** ?

Then again I may be totally wrong without knowing more. Good luck!

**Comment by alsusrus** [comment]
@supersnail12345 that worked! Many thanks! Stay safe.

**Comment by supersnail12345** [comment]
@alsusrus Glad to hear! Have fun.

**Comment by mrcook** [comment]
Hi @alsusrus, thanks for reporting the issue, and I'm happy you have a resolution.

Thanks for the debugging @supersnail12345, your assement looks correct to me. I'll first do some research to see if there is more modern solution to this, otherwise I'll just make the change as you suggest.

Thanks.

**Comment by isoneguy** [comment]
zebrahead

**Comment by mrcook** [comment]
Fixed with https://github.com/dungeons-of-moria/umoria/commit/451f46d4aec1ebca70af3ae8c1da50da44ee02e9
