### ISSUE TITLE
Compiling via mingw64

### ISSUE THREAD

**Issue by DMforall** [dungeons-of-moria/umoria#31]
Running MSYS2 MinGW 64-bit on my Windows 10 PC. I think I have all the compile tools installed, but I may have installed something unnecessary which is causing the following conflict.

My cmake command seems to go properly but then I get the following error on make. It looks like 
a mingw64 include file "C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:289:15" has a typedef for INT which is conflicting with the INT in the enum in player.h. 

I have not done any c++ compiling in 20 years or so. 

Do I just need to somehow disinclude the winnt.h file? 
Or perhaps I should remove MSYS2 and restart with a fresh install of necessary packages. If so, what are the specific packages I need.
Any help would be appreciated.

**make
Scanning dependencies of target umoria
[  1%] Building CXX object CMakeFiles/umoria.dir/src/config.cpp.obj
In file included from C:/msys64/home/abram/umoria-master/src/headers.h:67,
                 from C:/msys64/home/abram/umoria-master/src/config.cpp:10:
C:/msys64/home/abram/umoria-master/src/player.h:22:5: error: 'INT' redeclared as different kind of entity
   22 |     INT,
      |     ^~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:8,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/home/abram/umoria-master/src/headers.h:19,
                 from C:/msys64/home/abram/umoria-master/src/config.cpp:10:

C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:289:15: note: previous declaration 'typedef int INT'
  289 |   typedef int INT;
      |               ^~~
make[2]: *** [CMakeFiles/umoria.dir/build.make:83: CMakeFiles/umoria.dir/src/config.cpp.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/umoria.dir/all] Error 2
make: *** [Makefile:104: all] Error 2**

**Comment by supersnail12345** [comment]
I had this same problem compiling a couple of weeks ago. For me, surrounding the *#include <windows.h>* with **#define INT not_named_int** and **#undef INT** like so:

`#define INT notnamedint
    #include <windows.h>
#undef INT`

Not sure if this will work for you, since I don't know a lot about your build setup. Good luck!

**Comment by DMforall** [comment]
Thanks! That helped. Then I got to 96% complete and got another error.
In "ui_io.cpp" I had to change the line

(void) strcpy(buffer, defaultName);
to
(void) strcpy(buffer, default_name);

Then success 100%

**Comment by supersnail12345** [comment]
Great! Have fun!

**Comment by mrcook** [comment]
Hi @DMforall / @supersnail12345, I was trying to run a Windows build yesterday evening and also encountered this INT issue. It was late and I haven't had a chance to look into this today, but I'll take a look as soon as I can.

**Comment by supersnail12345** [comment]
@mrcook I'm sure there's a cleaner way to fix it than my messy hack... I'll leave that to the experts though. Thanks for all the work you do!

**Comment by mrcook** [comment]
@supersnail12345, @DMforall, recent versions of Windows and/or MINGW have stopped liking the uppercase `INT` enum. I don't know if this is correct or not, but in anycase, I've reverted these back to the original naming by adding a prefix; `A_INT`, so all the `PlayerAttr` enums now have that.

Thanks again for the help.

Fix with https://github.com/dungeons-of-moria/umoria/commit/79330c165bccb76a414ba289de4ffd1011a5f3f6
