### ISSUE TITLE
Disable roguelike commands by default

### ISSUE THREAD

**Issue by andrewtweber** [dungeons-of-moria/umoria#37]
Just a suggestion, I really think it was a mistake to enable them by default. It's a big deterrent to new players.

Even I, as somebody who played Moria for years, had difficulty remembering how to toggle them off.

I've shared the game on another roguelike's forum (Attnam.com - forum for Iter Vehemens ad Necem), and the 2 people who have tried it both [expressed their confusion](https://attnam.com/posts/30597) about why their numpad didn't work, and I had to guide them on how to disable roguelike commands.

I also saw a [thread on Reddit](https://www.reddit.com/r/moriarl/comments/jre7ob/why_are_my_controls_all_messed_up_i_just/) recently where somebody had the same confusion.

I think if past experienced players (myself) and experienced roguelike players (folks on my forum / folks who use roguelike subreddits) are having confusion with this, it was a mistake.

**Comment by mrcook** [comment]
Hi Andrew, I did wonder when flipping this if it might cause some confusion. :)

The thing is, in my world most people I know only/mainly use a laptop. Except for hard-code gamers few people have PCs anymore, so they don't have access to a numpad.

What to do? :)

It's pretty typical for older roguelikes to be HJKL based, so I assumed that if your average person is running on a laptop, and they know they are playing a 25 y/o roguelike, they would accept this as default.

Good or bad assumption?

If we knew the typical kind of person to come and try moria, we could make a more informed decision. Are they hard-core gamers playing on their PC, laptop wielding developers, or casual gamers who probably only have a laptop?

Things to think about:

* do most newcomers actually have access to a numpad?
* with no numpad wouldn't they be just as confused?
* if numpad is present, would they be anymore likely to try it, or just jump straight to the arrow keys?
* do they have previous context on what roguelikes are?
* with roguelikes being somewhat confusing next to modern games wouldn't they need the manual* anyway?


`*` I recently added a `?` message (top-right) on game start, so [if they see it!] they can get to the keys screen easily enough.

I'm open minded on this and would be happy to change it back, but only if we can be certain it would actually reduce confusion.

**Comment by Alaharon123** [comment]
Wouldn't it be better to have users be able to use the arrow keys by default and then when they get around to reading the help files and such, discover the numpad? I don't know what's common in old roguelikes, but I grew up playing Moria on DOS and I'd expect numpad and I know fighting games use numpad in a similar way and when my keyboard arrow keys would break as a kid I'd switch to using the numpad and the last two laptops I bought came with a numpad and numpad is very intuitive whereas roguelike controls are weird unless you're already comfortable with them for some reason. Additionally, I imagine a decent amount of people come to Moria from Angband or Zangband and those games use numpad by default just like their parent. Moria controls would seem to me to be the most intuitive default to choose for Moria.

**Comment by mrcook** [comment]
Hey Alaharon123,

I feel we're still trying to second guess what kind of people will want to try the game, and defaulting to controls based on our own experiences. My first reply covers most of my concerns on that so I won't repeat those.

One thing I didn't mention were comments made by Darren Grey on an old episode of the Roguelike Radio podcast. If I remember correctly Darren was discussing the topic about control systems and he himself mentioned the fact that most people these days (this was maybe 4 or 5 years ago) run on laptops that don't have numpads, which aligns with my understanding of the situation.

Perhaps the best way to resolve this is to not have defaults at all, but allow the player to chose their preferred keys the first time they run the game -- something to think about for sure.

Michael

**Comment by Dr-WaSaBi** [comment]
I use have a laptop with no num pad.  So having the arrow keys right from the get go would be great, or like @mrcook said maybe it could be a choice on first run?

Just my two cents.
Thanks
Russ

**Comment by mrcook** [comment]
Asking the player seems like a reasonble thing to do so I've added an item to the backlog in the projects page. There are however other things on the list I would like to get done first, but with all that's going in the world those are going to have to wait a little. Once things get back to normal, I'll push on with the work I've already started.

I think this issue can be closed for now.
