### ISSUE TITLE
Edge case causes destruction of primary weapon

### ISSUE THREAD

**Issue by russell-taylor** [dungeons-of-moria/umoria#39]
When I have a full inventory (a-v), I have two sets of bolts (or arrows), and I shoot and miss a monster and then pick up one of the bolts sometimes my inventory shows it as a single bolt and my inventory has an extra entry (a-w).  When I finally get this sorted out, my primary weapon has disappeared.

The disappearing primary weapon has happened to me on at least 2 characters (and at least twice on one) but this was the first time I caught it in the act.

**Comment by russell-taylor** [comment]
By disappeared, I mean that the slot is empty and I have no primary weapon.  It is not in my inventory and it is not lying around on the ground.

**Comment by mrcook** [comment]
Thanks for the bug report Russell. The merging of inventory is not really a major issue - I'll have to see if the old 5.6 code also worked in this way - but loosing your primary weapon is certainly a catastrophe!

There should be enough info here for me to make some experiments, thanks.

**Comment by mrcook** [comment]
Hi @russell-taylor, I managed to play around with this issue this morning. I haven't yet encountered the vanishing primary weapon but I did reproduce the extra inventory entry (`w`). On Umoria 5.6 arrows are always merged with others, at least when your inventory is full.

In addition to that I noticed another bug related to projectiles.

When firing shots into open spaces:

* only one arrow character (`{`) if left on the ground, but there should be multiple 
* that one character is always at the same distance
* when picking up an arrow no message is shown, and no arrow is added to the inventory
* when no more space is available for more arrows, a "it disapeared" message should be shown; it's not

A quick way to test this is during Wizard Mode (`CTRL-W`).

If we're lucky, once the above issues are fixed it will also solve those you encountered. I'll take a look at the code when I'm next able.

**Comment by russell-taylor** [comment]
Thanks for checking.  I the meantime, I'm just not picking back up lost bolts when I have a full inventory.  Presumably they behave the same way as arrows.  By the way, this happened for me when I had two different sets of bolts (with different characteristics) in inventory.

**Comment by mrcook** [comment]
Yes, the same for bolts and arrows, although the points I gave above probably happen on anything that is thrown. I think the next step is for me to examine the code and compare against v5.6, which is known to be correct. With luck it'll be straight forward to track down.

**Comment by mrcook** [comment]
A quick update: I was able to fix the [throwing items bug](https://github.com/dungeons-of-moria/umoria/commit/ca135fda382bf206a010f9f9550cf4fa299bd2a9), but alas still not the stacking issue. I checked over the various pickup/drop functions (e.g. `inventoryCarryItem()`, `inventoryDestroyItem()`) and related stacking functions, but was unable find a fix.

When I next have a chance to look at this I'll re-check those, then dig further.

**Comment by russell-taylor** [comment]
Thank you!  I'll pull down the new version and try it out.

**Comment by russell-taylor** [comment]
Just pulled master today and am still having trouble with the bolts not merging back into my inventory when I pick them up.  I have two sets of bolts and when they are picked up they form a new inventory list.  I've been afraid to try when I'm full up so I don't know if they would still destroy my primary weapon.  Thanks for looking into it, and for maintaining umoria!

**Comment by mrcook** [comment]
Hi Russell, as mentioned in my last comment, "I checked...related stacking functions, but was unable find a fix" :)

It seems there were two bugs related to throwing; the distance and randomness of where an item (e.g. bolt) would land when being thrown, and then when picking it up, as you noted, which seems to be related to how items of the same type are stacked together in the inventory.

I checked some of the drop/pickup related functions but was unable to find why this is happening. I'm going to be looking deeper into that as soon as I have a chance.

**Comment by mrcook** [comment]
Hi @russell-taylor, I've pushed what I hope is a fix for the stacking items bug! A silly mistake really: https://github.com/dungeons-of-moria/umoria/commit/bf0cdb065c0a15f3c0a69f25e1ecd42c777941dc

I've yet to encounter the vanishing weapon, although it is possible it was related to this last commit.

Michael

**Comment by russell-taylor** [comment]
Awesome!  It looks like that fixed it.  I can pick up my bolts again without living in fear!  That's a big deal with my HA lance...  Thank you!

**Comment by mrcook** [comment]
No problem Russell, I'm just sorry it took so long. Good luck!
