### ISSUE TITLE
Fails to compile on macOS using Xcode 12.5.1

### ISSUE THREAD

**Issue by yesmar** [dungeons-of-moria/umoria#45]
I get two errors attempting to compile on macOS 11.4 using Xcode 12.5.1 (clang 12.0.5). In both cases the error is
```
anonymous non-C-compatible type given name for linkage purposes by typedef declaration; add a tag name here [-Werror,-Wnon-c-typedef-for-linkage]
```
This error occurs on `Game_t` in game.h and `Player_t` in player.h. It seems to have to do with linkage of anonymous structs. (Possibly because they embed other anonymous structs?)

**Comment by mrcook** [comment]
Fixed by https://github.com/dungeons-of-moria/umoria/commit/3a11113a7cd977b1e6407dbb2fd5931ba20039c6
