### ISSUE TITLE
Incorrect Description When Dropping Multiple Items

### ISSUE THREAD

**Issue by jhirschberg70** [dungeons-of-moria/umoria#48]
I am playing version 5.7.15 on Ubuntu 20.04.2 LTS using the Umoria keyboard layout.

If you have multiple of the same item and attempt to drop them, a . is being inserted into the description that shouldn't be there.  For example, say you have 5 rations of food in inventory slot a.  If you type d to initiate a drop command followed by a to select inventory slot a you see this message:

"Drop all 5 Ration. of Food? [y/n]"

There is a . in place of the s in Rations.  I would expect the message to be

"Drop all 5 Rations of Food? [y/n]"

The culprit seems to be line 822 of ui_inventory.cpp in the executeDropItemCommand function.  There is no comment about what this line is supposed to be doing, and from my brief examination of the code, it seems like it should just be deleted.  It doesn't seem like there would be a scenario where you'd want to overwrite a character in the middle of the description with a period, but again, I don't know the code that well.

**Comment by mrcook** [comment]
Hi jhirschberg70, many thanks for the bug report, and my apologies for the later reply.

I have some time off work next week so I'm going to dedicate a morning to looking into this, and another bug that's been reported.

Thanks,
Michael

**Comment by jhirschberg70** [comment]
Thanks, Michael.  I've actually come across a couple other issues which I'll submit when I have a little more time.

Jeff

**Comment by mrcook** [comment]
Hi @jhirschberg70,

This seems to be a left over from the refactoring I did. In the original code the period is replaced by a question mark and once that string has been used in a sprintf, the question mark is replaced again by a period. This can be found in the [moria1.c file](https://github.com/dungeons-of-moria/umoria/blob/v5.6.0/source/moria1.c#L1166-L1169):

```
  prt1[strlen(prt1)-1] = '?';
  (void) sprintf(prt2, "Drop all %s [y/n]", prt1);
  prt1[strlen(prt1)-1] = '.';
  prt(prt2, 0, 0);
```

Perhaps back when this was part of that 350 line while loop it mattered. But I agree, it makes no sense in this scenario. A quick test also shows no ill effect, so I'll go ahead and commit the change.

**Comment by jhirschberg70** [comment]
Thanks, Michael!  I've found another issue related to dropping items, and I think I have a solution.  I need a little time to write up the issue and possible fix, which I will do this weekend.

Jeff

**Comment by mrcook** [comment]
Fixed with commit https://github.com/dungeons-of-moria/umoria/commit/3682df99d09fd7ad2c4e5d11281a103751c9fe9a

Thanks again Jeff.
