### ISSUE TITLE
Incorrect GPL Version Reference in Help Message

### ISSUE THREAD

**Issue by jhirschberg70** [dungeons-of-moria/umoria#49]
I am playing version 5.7.15 on Ubuntu 20.04.2 LTS using the Umoria keyboard layout.

When executing umoria with the -h command-line option,  the following prints to the screen:

<pre>Robert A. Koeneke&apos;s classic dungeon crawler.
Umoria 5.7.15 is released under a GPL v2 license.

Usage:
    umoria [OPTIONS] SAVEGAME

SAVEGAME is an optional save game filename (default: game.sav)

Options:
    -n           Force start of new game
    -d           Display high scores and exit
    -s NUMBER    Game Seed, as a decimal number (max: 2147483647)

    -v           Print version info and exit
    -h           Display this message
</pre>

Note that line 2 says "Umoria 5.7.15 is released under a GPL v2 license."  It should read "Umoria 5.7.15 is released under a GPL v3 license."  Changing v2 in line 87 of main.cpp to v3 should fix the issue.

**Comment by mrcook** [comment]
Fixed with commit https://github.com/dungeons-of-moria/umoria/commit/1979b8601c5f94de7ccacdb83b4d4ac1a0948815
