### ISSUE TITLE
scores.dat File in Repository Not Empty

### ISSUE THREAD

**Issue by jhirschberg70** [dungeons-of-moria/umoria#51]
The scores.dat file in the repository appears to contain the score from a test character named test, a human mage killed by interrupting.  I'm thinking this was inadvertently added to the repository.

**Comment by mrcook** [comment]
You're probably right, however, this looks to have happened on the 5.6 GPL release, so for the moment I don't want to change that :)

See: https://github.com/dungeons-of-moria/umoria/blob/v5.6.0/files/scores
