### ISSUE TITLE
Punctuation error on character generation screen

### ISSUE THREAD

**Issue by mrcook** [dungeons-of-moria/umoria#52]
(This was an issue submitted via email)

I'm running this via the terminal on Windows (latest version of Umoria) and there's no punctuation mark between the parentage and family standing lines:

> Character Background
> You are one of several children You are a well liked child. You have dark brown eyes, wavy brown hair, and an average complexion.

On this re-roll, the human character's social class is only 9, so maybe the lack of stated parentage (serf, landed knight, etc.) indicates that I'm unacknowledged. If this were the case, though, wouldn't it just say: "You are one of several children. You are a well liked child."? It makes me think that something isn't printing out that should be.

**Comment by mrcook** [comment]
This can be reproduced by setting the [dice roll in character creation](https://github.com/dungeons-of-moria/umoria/blob/master/src/character.cpp#L189) to `100`:

`int test_roll = 100; // randomNumber(100);`

I'm still investigating why this happens.

**Comment by awjackson** [comment]
This is a duplicate of https://github.com/dungeons-of-moria/umoria/issues/62 and can be closed.

**Comment by mrcook** [comment]
Thanks @awjackson closing.
