### ISSUE TITLE
Adding Support for Playing in a Browser

### ISSUE THREAD

**Issue by jhirschberg70** [dungeons-of-moria/umoria#53]
For the past couple months I've been spending my spare time trying to make Umoria run in a browser using [emscripten](https://emscripten.org/) to compile to [WASM.](https://webassembly.org/)  I'm not the first to do this (see Donnie Russell's port [here](http://donnierussellii.github.io/JSMoria.html)) but my approach and intent (I believe) are different.  

1.  Minimize changes to the code base.  I think I've been reasonably successful with that, as I've only had to modify three headers and two cpp files from the current code base.  The modifications consist of ```#ifdefs``` around small sections of code.  I also added one new header, two new cpp files, a javascript file and an HTML file.

2. Use javascript and HTML for the IO.  Donnie Russell's version uses SDL, which is supported in emscripten and may be the better choice.  Rather than duplicate his efforts, I figured I'd go the route of using what a browser provides natively to see if it would work.  It seems to.  I do see some slow down when there are a large number of monsters on the screen.  I need to do more profiling, but I don't think that's due to rendering or handling input.  WASM doesn't run as fast as native code, so slower performance is to be expected.

3. Duplicate native look and feel.  Aside from the aforementioned slow downs with a large number of monsters onscreen, I believe the game plays very much like a native build.  I implemented a bell sound in browser for the ```terminalBellSound()``` function, as well as a cursor.  Command line arguments work through URL query parameters.

4. Create a universal "executable".  While what I've put together could be hosted on a server, I was looking at it as more of a cross-platform "executable" that will run on any platform with a modern browser.  The build process creates a single HTML file that you load in the browser.  Scores and save files are stored in IndexedDB.  I've played in Firefox, Chrome and Opera on Linux and Chrome and Edge on Windows, and so far things seem to be functioning properly.  I don't have access to a Mac to try Safari.  In theory, building for a browser allows you to pick your platform of choice for development, build once and have cross-platform compatibility from that single build.  I've confined myself to Linux on a PC for development, so I can't speak to what it would take to build on other platforms.

Aside from the fun I've had working on this, and what I've learned, my hope is that my changes might become part of the repository.  Obviously, that's ultimately up to @mrcook, but rather than just submit a pull request, I thought I'd post here to see if anybody has any interest/opinions.  If it turns out that this would work better as a fork, then that's fine with me.

**Comment by mrcook** [comment]
Hi Jeff,

It's interesting to hear that it didn't take much to port this, so thanks for sharing your findings.

I think it's cool, but probably not suitable for inclusion here. At the end of the day I will be the one responsible for maintaining the code going forward and I feel there are far more important updates needed first -- unfortunately other things in my life keep having a higher priority, and I'm not sure when I'll even get around to those.

I'll keep this issue open for a while so others get a chance to see it --- please do share a link to your repo though!

**Comment by jhirschberg70** [comment]
Hi, Michael,

I completely understand.  I'm hoping to have the fork all set up this coming weekend, and I'll post the link.

If you've never checked out emscripten, I recommend it.  The amount of work that's gone into it and what you can do with it is really impressive.

**Comment by jhirschberg70** [comment]
Okay, I've finally had some time to fork the Umoria repository and add everything for building to run in a browser.  You can find the for at [https://github.com/jhirschberg70/browser-based-umoria](url).

**Comment by mrcook** [comment]
Cool, it works great!

Would you be interested in me hosting the html file on the Umoria website? I think it could live at the URL umoria.org/play

**Comment by jhirschberg70** [comment]
Thanks for offering to host the file, Michael!  That would be great!

Jeff

**Comment by mrcook** [comment]
Great, thanks Jeff. I'll try to get that done this week.

**Comment by jhirschberg70** [comment]
Thanks, Michael!

Jeff
