### ISSUE TITLE
color umoria?

### ISSUE THREAD

**Issue by dchmelik** [dungeons-of-moria/umoria#56]
Might it be possible to add in [color umoria](https://github.com/andrewtweber/umoria-color) as an option?  It was updated in recent years but now has two compilation errors and I haven't heard back from the uploader/maintainer...

**Comment by mrcook** [comment]
Hi David, I'm afraid this isn't something I'm interesting adding at this time.

It is probable that those compilation errors are present here too. I have some time off work next month, so I will try to do a refresh and make sure everything is compiling correctly.

**Comment by dchmelik** [comment]
Yes; similar/same issue...
```
dcosmos:~/math/src/games/roguelike/moria_angband_tome/umoria$ make
Consolidate compiler generated dependencies of target umoria
[  1%] Building CXX object CMakeFiles/umoria.dir/src/game_save.cpp.o
/home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp: In function ‘bool loadGame(bool&)’:
/home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp:810:29: error: array subscript 66 is above array bounds of ‘Tile_t [66][198]’ [-Werror=array-bounds]
  810 |                 if (tile >= &dg.floor[MAX_HEIGHT][0]) {
      |                             ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/headers.h:59,
                 from /home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/game_save.cpp:8:
/home/d/math/src/games/roguelike/moria_angband_tome/umoria/src/dungeon.h:55:12: note: while referencing ‘Dungeon_t::floor’
   55 |     Tile_t floor[MAX_HEIGHT][MAX_WIDTH];
      |            ^~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/umoria.dir/build.make:370: CMakeFiles/umoria.dir/src/game_save.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/umoria.dir/all] Error 2
make: *** [Makefile:91: all] Error 2
```

**Comment by acahir** [comment]
When updating moria to compile on macOS, I added a few new things:
- color support
- option to disable haggling
- speed mode (increased player odds in finding special items/casting identity spells etc)

These changes are in https://github.com/acahir/moria, I'd be willing to consider rolling them into this version if that is of any interest.

**Comment by acahir** [comment]
#59 PR added for color support

**Comment by mrcook** [comment]
Hi @acahir , my apologies for not noticing your comment from last week. I've actually made a comment on your PR.

@dchmelik I think in general Andrew Weber only adds colour support on top of the code from this repository. You can therefore blame me for umoria-color not compiling. Hopefully now that the compile errors [have been fixed](https://github.com/dungeons-of-moria/umoria/commit/71dad4103b5c8f3e1f7723eb14d14425755e7ba5), Andrew will pull in the latest changes.

Thanks,
Michael
