### ISSUE TITLE
Error in Definition of character_backgrounds Array

### ISSUE THREAD

**Issue by jhirschberg70** [dungeons-of-moria/umoria#62]
I am playing version 5.7.15 on Ubuntu 22.04.1 LTS using the Umoria keyboard layout.

Somewhere along the line, a bug was introduced into the definition of the `character_backgrounds` array.  `character_backgrounds[127]` is currently defined as

`{"of a Royal Blood Line.  ",                            100,  2,  3, 140},`

Based on my understanding of the code, this entry is meant for generating histories for Humans and Half-Elves (chart value of 2, next value of 3), In its current location in the array, this data will never be used. This entry should be moved to `character_backgrounds[10]`. If you look at the equivalent `background` array in versions up through 5.2, you'll see that's where it's located. 

In 5.7.15, if you happen to roll 100 when generating the portion of the history for a Human or Half-Elf that comes from chart 2, the code falls through to chart 3 and it's entry for a roll of 100, `character_backgrounds[12]` in 5.7.15. Thus, the character will never have the associated parentage and social class modifier and will always be "a well liked child."

I can submit a pull request with the fix, if you'd like.

**Comment by mrcook** [comment]
Well, that's a bit worrying...

Hi Jeff, thanks for the catch!

What I find worrying is that this change happened during a clang-tidy/clang-format run right at the start of my work on the project. You can see it here: https://github.com/dungeons-of-moria/umoria/commit/43ce8207e6ce1181add3a605f6e66dfdf69c42cf. Let's just hope this didn't mess up anything else.

You are more than welcome to create a PR, but also no problem if you'd rather not.

Cheers,
Michael

**Comment by jhirschberg70** [comment]
PR #64 submitted.

Cheers,

Jeff

**Comment by mrcook** [comment]
Fix by https://github.com/dungeons-of-moria/umoria/pull/64
