### ISSUE TITLE
sprintf deprecated

### ISSUE THREAD

**Issue by r7st** [dungeons-of-moria/umoria#67]
Building on MacOS Ventura 13.2
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: x86_64-apple-darwin22.3.0

`error: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Werror,-Wdeprecated-declarations]`

required building with:

`CMAKE_CXX_FLAGS+="-Wno-deprecated-declarations"`

**Comment by mrcook** [comment]
Thanks for the issue @r7st. I've recently gained access to macos after being without for the last couple of years so once I get a chance I'll take a look at this.

**Comment by bcoffin9** [comment]
Any updates on this? I'm also on a mac, seeing the same issue.

**Comment by mrcook** [comment]
Fix with https://github.com/dungeons-of-moria/umoria/commit/c1f5a824b1027dd8f83adce76c37b90629a5c3b8

Sorry for the delay....hopefully I didn't break anything!

**Comment by bcoffin9** [comment]
Looks great!! I had the same changes in my fork too :) thanks!!
