### ISSUE TITLE
CLI option for enabling roguelike keys missing

### ISSUE THREAD

**Issue by mfandl** [dungeons-of-moria/umoria#68]
In v5.7.12 the roguelike keys mode was enabled by default and the CLI option to start moria with this mode was removed. In v5.7.14 the default was reverted back to moria mode, but the CLI option was not added back.

Would it be welcome adding this back? I'll gladly do it.

**Comment by mrcook** [comment]
It's now possible to use the `-r` flag to enable roguelike keys at startup. Please note that any setting in the game.sav file will have priority.

Fixed with: https://github.com/dungeons-of-moria/umoria/commit/49a25d7b11b9bba198b9ade4f881d33358dd9460
