### ISSUE TITLE
Disarming in character sheet wrong value

### ISSUE THREAD

**Issue by takosalad** [dungeons-of-moria/umoria#74]
I tried disarming a basic sleep trap on dlevel 1 for 50 times with "Fair" Disarming ability and failed all 50 times.

**Comment by mrcook** [comment]
Thanks or the issue. I'm not sure when I'll get around to looking into this but I'll leave this here for future reference.

**Comment by awjackson** [comment]
https://github.com/dungeons-of-moria/umoria/pull/78 fixes this.
