### ISSUE TITLE
wizard mode partly broken

### ISSUE THREAD

**Issue by dchmelik** [dungeons-of-moria/umoria#75]
If one plays an elf ranger in wizard mode (I also used \<CTRL\>e to maximize everything including speed) hunger occurs almost every other action/movement so you die fast, making the game almost unplayable in that mode.  It didn't happen as other characters such as human warrior (after maximizing everything including speed).  I don't know if it happens with other races & classes.

**Comment by mrcook** [comment]
Thanks for the bug report. I'm not sure when I'll have time to look into this but I'll leave this issue open for future reference.

**Comment by awjackson** [comment]
I don't think this is a bug. If you are faster than normal for any reason, you consume extra food in proportion to your speed squared (see `playerFoodConsumption()` in `game_run.cpp`). As for why the effect was obvious with one character but not with another character, they probably pressed + in the wizard menu to adjust speed a different number of times with each character.

**Comment by dchmelik** [comment]
> I don't think this is a bug

It is.

>If you are faster than normal for any reason, you consume extra food in proportion to your speed squared [...]

Sure, but not as fast as it happens in this case.  I've played wizard mode Moria since early 1990s with maximum speed and this never happened.

> As for why the effect was obvious with one character but not with another character, they probably pressed + in the wizard menu to adjust speed a different number of times with each character.

No: I tested carefully.

**Comment by awjackson** [comment]
In order to try to reproduce this, I need to know what you mean by "maximum speed". There isn't a command in wizard mode to set player speed to a specific value, only to change it one step at a time. How many times do you increment speed to achieve what you consider "maximum speed"?

**Comment by dchmelik** [comment]
Clearly increment until gets maximum--a specific value (won't go past) I don't recall.

**Comment by awjackson** [comment]
Pressing + once at the "alter speed?" prompt causes the displayed speed to become "Fast". Pressing + a second time causes it to become "Very Fast". After that the character will continue to become faster, but there is no visible feedback until a total of (I assume from the code, didn't count) 32768 presses, whereupon an integer overflow occurs and the speed rolls around to "Very Slow". There is no "maximum value it won't go past", unless you mean this overflow. The character will starve to death in one move after only a few dozen presses of +, long before the overflow occurs.

All of this behaviour is exactly the same as in 5.5.2. If you played a version where altering speed from the wizard menu worked differently, it was a patched version.

Incidentally, the fastest speed achievable in normal gameplay is 3 (one notch past "Very Fast"). This requires a +1 speed ring, +1 speed boots, and a haste potion or spell (umoria doesn't generate speed items with a plus larger than +1).

**Comment by dchmelik** [comment]
I see.  Then its inadequate if doesn't show speed number, but not working differently than designed.
