### ISSUE TITLE
Looking for old umoria sources (as old as possible) for VAX/VMS C 

### ISSUE THREAD

**Issue by vaxorcist** [dungeons-of-moria/umoria#77]
Hi,
I'm running old VAXen (as well SIMH as real ones) with old versions of VMS (V1 to V4).
Because of this, I'd like to run old games as well ;-))
Can you help?

Regards
Ulli, the VAXorcist

**Comment by vaxorcist** [comment]
Forgot to mention: VAX/VMS PASCAL will do as well!

**Comment by vaxorcist** [comment]
Hi Michael,
thanks for the link and your work preserving Moria and Umoria. Can you
describe the difference between the two?
I plan to provide a pre-configured SIMH VAX instance to run VMS Moria on,
so that everyone who likes can play it without a real VAX. There will be no
VMS license issues,  because VMS V4.7 (the version I'm going to use) has
got no licensing mechanism.
I'll keep you informed about my progress.
Cheers,
Ulli


Michael R. Cook ***@***.***> schrieb am Di., 30. Jan. 2024,
18:11:

**Comment by mrcook** [comment]
Happy to hear you got it up and running! :)

As for the differences: well, Umoria was a continuation of the original VMS Moria, but with lots of bug fixes and new features. If you'd like a more detailed breakdown, I created a history page with the changelog highlights: https://umoria.org/highlights/

**Comment by dchmelik** [comment]
Don't know this runs on VAX Pascal anymore but has bugfixes: [M3wP/MoriaOP](http://github.com/M3wP/MoriaOP).

**Comment by vaxorcist** [comment]
Hi David,
thanks for your hint, I will try this newer version on VAX PASCAL when I
finished my work on VMS MORIA V4.43.

Ulli

Am Sa., 3. Feb. 2024 um 07:37 Uhr schrieb David Chmelik <
***@***.***>:

**Comment by vaxorcist** [comment]
Hi Michael,
thanks a lot for the detailed history of UMORIA!.
Maybe I'll try to apply some of the later bugfixes to VMS MORIA when I
finished my work on version 4.43.
I will have to learn some VMS PASCAL first - up to now I'm halfway fit in
FORTRAN only ...

Everything is fine so far except for the MORIA online help file
*[EXECUTE]MORIAHLP.HLB*.
This is a VMS binary library file is a special format that might have been
corrupted along the way, i.e. it does not work yet.
If you have access to the library source file of MORIAHLP (which is plain
ASCII), this would be of great help!
Otherwise it might be fixable, too, but with much more effort.

Ulli

Am Fr., 2. Feb. 2024 um 17:32 Uhr schrieb Michael R. Cook <
***@***.***>:

**Comment by vaxorcist** [comment]
Great, that does indeed look like a help file source! I'll try to get that
into a library file.

Ulli


Am So., 4. Feb. 2024 um 20:19 Uhr schrieb Michael R. Cook <
***@***.***>:

**Comment by vaxorcist** [comment]
Yes, we've got a working help library now!
At the moment I'm struggling with constantly multiplying "Giant White Lice"
attacking me and I'm locked in a room without obvious escape ...
Can you give me a hint what to do?
Ulli

Am So., 4. Feb. 2024 um 22:13 Uhr schrieb Hans-Ulrich Hölscher <
***@***.***>:

**Comment by vaxorcist** [comment]
The VMS MORIA kit is available now online: https://gunkies.org/wiki/MORIA
Could you please have a look and check it?

Ulli

P.S. Feel free to distribute/offer it in other places!

Am Mo., 5. Feb. 2024 um 10:13 Uhr schrieb Hans-Ulrich Hölscher <
***@***.***>:

**Comment by mrcook** [comment]
As I have no direct knowledge of this VMS related stuff, I'll leave that in your hands. Looks good though :)
