### ISSUE TITLE
mac installation

### ISSUE THREAD

**Issue by AtmPhys** [dungeons-of-moria/umoria#8]
I'm having issues when I try to install this on a Mac (OS 10.10.5). I have gcc-6.3 and ncurses-6.0, and I'm getting the following error when I type in the 'make package' command:

[  2%] Building CXX object CMakeFiles/umoria.dir/src/data_creatures.cpp.o
error: unknown warning option '-Wunsafe-loop-optimizations'; did you mean
      '-Wunavailable-declarations'? [-Werror,-Wunknown-warning-option]
make[2]: *** [CMakeFiles/umoria.dir/src/data_creatures.cpp.o] Error 1
make[1]: *** [CMakeFiles/umoria.dir/all] Error 2
make: *** [all] Error 2

Any ideas?

**Comment by sdicke** [comment]
A possible workaround would be a special rule for building on macOS to disable -Wunsafe-loop-optimizations.

**Comment by sdicke** [comment]
You should be able to build umoria if you remove -Wunsafe-loop-optimizations in CMakeFiles/umoria.dir/flags.make

**Comment by mrcook** [comment]
Yes, as Sebastian says, remove that warning and it will compile. You can also temporarily remove it from the `CMakeLists.txt` and try again with;
```
$ cmake .
$ make install
```
As this breaks compatibility with GCC 6, I'll go ahead and removed it from the project.

**Comment by mrcook** [comment]
Commit https://github.com/dungeons-of-moria/umoria/commit/c13d5978f6104ddcdec2db720ba943351f45ea58 fixes this issue.

**Comment by AtmPhys** [comment]
Okay, now I have some new (different) issues. Replacing the flag '-Wunsafe-loop-optimizations' with '-Wunavailable-declarations' seems to work. When I try to run the 'make packages' command, I now get this error:

> /Users/.../umoria-master/src/death.cpp:399:4: error: function declared
>       '[[noreturn]]' after its first declaration
> [[ noreturn ]] void exitGame() {
>    ^
> /Users/.../umoria-master/src/externs.h:166:6: note: declaration missing
>       '[[noreturn]]' attribute is here
> void exitGame();
>      ^

I tried modifying line 166 in externs.h to add the attribute no return in the function declaration:

> void exitGame() __attribute__((noreturn));

But I still got the same error; I'm not sure if I have the syntax wrong?
