### ISSUE TITLE
Typos in README.md

### ISSUE THREAD

**Issue by crush401991** [dungeons-of-moria/umoria#81]
Hello, I found a couple typos while reading the README on this project:

first paragraph:
being ported to the C language by James E. Wilson in 1988, and released a Umoria.
being ported to the C language by James E. Wilson in 1988, and released _**as**_ Umoria.

A note in this section: [Umoria 5.7.x releases](https://github.com/dungeons-of-moria/umoria/blob/master/README.md#umoria-57x-releases) 
Note: there have been no intentional game play changes in the 5.7.x releases.
Note: there have been no intentional _**gameplay**_ changes in the 5.7.x releases.

**Comment by mrcook** [comment]
Many thanks for the info @crush401991 . They are now fixed.
