### ISSUE TITLE
Add images to the README.md

### ISSUE THREAD

**Issue by crush401991** [dungeons-of-moria/umoria#82]
Hi, I wanted to ask if I could make a pull request involving a couple changes to the README.md.
I hoped to include a little more information about the game (such as how its based on The Lord of the Rings), along with some images/screenshots of the gameplay. I have a draft almost ready with a few changes and images, but I don't want to fork and make a pull request if that's unwanted.

I noticed a lot of other games and projects on github include some images to show what the game is like (for example if its 2d or 3d).
As someone who has never heard of Umoria and was just looking at games on github, it was a real surprise to learn it was text-based, which I didn't find out until trying to play it.

Sorry if this isn't the right place to ask this!

Also, while I do genuinely think the README would benefit from some screenshots of the game, I feel like I should be honest here. Half the reason I want to make the pull request myself is that I am taking a class on open source software and we are required to make a contribution/pull request to an open source project. The change itself doesn't have to be accepted, luckily, but we need to show that we at least made a pull (if the issue was approved).
If it's not too much trouble, could I make a pull request with some changes to the README? Again, it doesn't have to be accepted, just made.

I'm asking first because I don't want to overstep if you don't think its a necessary change.

**Comment by mrcook** [comment]
Hi @crush401991, thanks for your suggestion, and your honesty for giving it. However, I do not think this project is the best place for those things.

The very nature of the basic ASCII graphics in a classic Roguelike like this means images don't bring much benefit. I'm also not sure adding that kind of information about the game will add anything further than what's already in the current [/historical](https://github.com/dungeons-of-moria/umoria/tree/master/historical) docs. Places like [RogueBasin](https://www.roguebasin.com/index.php/Moria), Wikipedia, etc., would be more suitable.

I very much appreciate your previous message regarding the typo's, but I feel this one is not suitable to pursue.

Regards,
Michael

**Comment by crush401991** [comment]
thanks for letting me know!
